version: '2'
services:
  cron:
    scale: 1
    start_on_create: true
  worker:
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 6379
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  sentry:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 600000
      interval: 60000
      strategy: recreate
      request_line: GET "/auth/login/sentry/" "HTTP/1.0"
      reinitializing_timeout: 60000
